name: wilatone_restaurant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #StateManagment
  get: ^4.6.6
  get_storage: ^2.1.1

  #date format
  intl: ^0.19.0

  #image view
  flutter_svg: ^2.0.9

  flutter_screenutil: ^5.9.0
  flutter_inappwebview: ^5.8.0
  connectivity_plus: ^5.0.2
  pinput: ^3.0.1
  intl_phone_field:
    path: packages/intl_phone_field-master

  #charts
  fl_chart: ^0.66.0
  syncfusion_flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

